name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@446a96a6fee94b9952e9da3049d4353a3387650c # v2025.07.22.02
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
